import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './_components/navbar'
import ToastProvider from '@/components/provider/toast-provider'
import ModalProvider from '@/components/provider/modal-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ToastProvider />
        <ModalProvider />
        <Navbar />
        {children}
      </body>
    </html>
  )
}
